config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
    resources :words
    root "static_pages#home"
  end
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :categories, only: [:index]
  resources :words, only: [:index, :show]
  resources :categories do
    resources :lessons
  end
  resources :lessons, only: [:index, :destroy]
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :lessons, through: :result
  has_many :results
  has_many :answers, dependent: :destroy, inverse_of: :word

  scope :order_name, ->{order :name}
  scope :of_category, ->category_id {where category_id: category_id}
  scope :search_name, ->search do
    where("name LIKE ?", "%#{search}%") if search.present?
  end
  scope :random, -> do
    order("RANDOM()").limit Settings.per_lesson.words
  end

  validates :name, presence: true, length: {maximum: 140}
  validates :content, presence: true
  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|attribute| attribute[:answer_content].blank?}
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, :logged_in_as_admin
  before_action :load_data, only: [:create, :index, :edit]
  before_action :load_word, only: [:destroy, :show, :edit, :update]

  def index
    @word = Word.new
    @word.answers.build
  end

  def show
    @answers = @word.answers.all
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t "flash.edit_success"
      redirect_to admin_words_path @word
    else
      render :edit
    end
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t "word_created"
      redirect_to admin_words_path
    else
      render :index
    end
  end

  def destroy
    if @word.destroy
      flash[:sucess] = t "word_deleted_success"
    else
      flash[:danger] = t "word_deleted_fail"
    end
    redirect_to :back
  end

  private
    def word_params
      params.require(:word).permit :name, :content, :category_id,
        answers_attributes: [:id, :answer_content, :is_correct, :_destroy]
    end

    def load_data
      @words = Word.search_name(params[:search]).order_name
        .paginate page: params[:page], per_page: Settings.per_page.words
      @categories = Category.all
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.search_name(params[:search]).order_name
      .paginate page: params[:page], per_page: Settings.per_page.words
  end

  def show
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:warning] = t "record_isnt_exist"
      redirect_to words_path
    end
  end
end

app/views/admin/words/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for [:admin, @word] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <%= f.select :category_id,
      @categories.collect { |p| [ p.name, p.id ] }, {}, {class: "form-control"} %>
    <%= f.text_field :name, class: "form-control",
      placeholder: t("word_name") %>
    <%= f.text_area :content, class: "form-control",
      placeholder: t("word_description") %>
    <div class="form-group box-answers">
      <%= f.fields_for :answers do |af| %>
        <%= af.text_field :answer_content, class: "form-control",
          placeholder: t("answer_content") %>
        <%= af.check_box :is_correct, class: "form-checkbox" %>
        <p><%= t("true_answer") %></p>
        <%= af.check_box :_destroy, class: "checkbox-remove" %>
        <p1><%= t("remove") %></p1>
      <% end %>
      <button type="button"
        class="btn btn-success text-center add-answer"><%= t "btn_add_answer" %>
      </button>
    </div>
    <%= f.submit t("post_word"), class: "btn btn-primary text-center" %>
  <% end %>
  </div>
</div>

app/views/admin/words/_search_form.html.erb
<div id="search-form">
  <%= form_tag admin_words_path, method: :get, class: "form-inline" do %>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <%= submit_tag t("search"), class: "form-control" %>
  <% end %>
</div>

app/views/admin/words/edit.html.erb
<% provide :title, t("word_show_title") %>
<div id="wrapper" >
  <%= render "layouts/admin/menu.html.erb" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="w3-container">
            <div class="row w3-ul w3-card-4">
              <br><h1><%= t "admin_word_create_new" %></h1>
              <div class="form-group">
                <%= render "form" %>
              </div><br>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t("word_show_title") %>
<div id="wrapper" >
  <%= render "layouts/admin/menu.html.erb" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="w3-container">
            <div class="row w3-ul w3-card-4">
              <br><h1><%= t "admin_word_create_new" %></h1>
              <div class="form-group">
                <%= render "form" %>
              </div><br>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <h1 class="page-header"><%= t "word_show_all" %></h1>
              </div>
            </div>
            <div class="row w3-ul w3-card-4">
              <div class="col-lg-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <%= t "word_show_all" %>
                    <div class="search-form">
                      <%= render "search_form" %>
                    </div>
                  </div>
                  <div class="panel-body">
                    <table
                      class="table table-striped table-bordered table-hover"
                      id="dataTables-example">
                      <thead>
                        <tr>
                          <th><%= t "word_table_word" %></th>
                          <th><%= t "word_table_content" %></th>
                          <th><%= t "word_table_category" %></th>
                          <th><%= t "word_table_time" %></th>
                          <th><%= t "word_table_admin" %></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% if @words.any? %>
                          <% @words.each do |word| %>
                            <tr class="odd gradeX">
                              <td><%= link_to word.name, word_path(word) %></td>
                              <td><%= word.content.truncate_words(
                                Settings.limit_content) %></td>
                              <td class="center"><%= word.category.name %></td>
                              <td><%= t "word_table_posted" %>
                                <%= time_ago_in_words(word.created_at) %>
                                <%= t "word_table_posted_end" %></td>
                              <td class = "last-column">
                                <%= link_to t("admin_word_show"), admin_word_path(word),
                                  class: "btn btn-info btn-mn" %>
                                <%= link_to t("admin_word_edit"), edit_admin_word_path(word),
                                  class: "btn btn-success btn-mn" %>
                                <%= link_to t("admin_word_delete"), admin_word_path(word),
                                  method: :delete, remote: true,
                                  data: {confirm: t(:"sure_delete")},
                                  class: "btn btn-danger btn-mn btn-custom" %>
                              </td>
                            </tr>
                          <% end %>
                        <% else %>
                          <h1><%= t "word_search_not" %></h1>
                        <% end %>
                      </tbody>
                    </table>
                    <%= will_paginate @words %>
                    <div class="well">
                      <h4><%= t "word_framgia" %></h4>
                      <p><%= t "word_framgia_list" %><a target="_blank"
                        href="http://recruit.framgia.vn/"><%= t "word_framgia_url" %>
                        </a>.
                      </p>
                      <a class="btn btn-default btn-lg btn-block"
                        target="_blank" href="http://framgia.com/jp/">
                        <%= t "word_framgia_home" %></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/show.html.erb
<% provide :title, t("word_show_title") %>
<div id="wrapper" >
  <%= render "layouts/admin/menu.html.erb" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h1><%= t "word_show_info" %></h1>
          <div class="w3-container">
            <div class="row category-info">
              <div class="col-md-4 title-word">
                <div class="top-word">
                  <h4><%= @word.name %></h4>
                </div>
                <div class="bot-content">
                  <p><%= @word.content %></p>
                </div>
              </div>
              <div class="col-md-8">
                <div class="row w3-ul w3-card-4">
                  <div class="col-lg-12">
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <%= t "answer_show_all" %>
                      </div>
                      <div class="panel-body">
                        <table width="100%"
                          class="table table-striped table-bordered table-hover"
                          id="dataTables-example">
                          <thead>
                            <tr>
                              <th><%= t "answer_table_answer" %></th>
                              <th><%= t "answer_table_answertf" %></th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @answers.each do |answer| %>
                              <tr class="odd gradeX">
                                <td><%= link_to answer.answer_content , "" %></td>
                                <td class="td-center">
                                <% if answer.is_correct? %>
                                  <%= image_tag "true.png", class: "img-tf" %>
                                <% else %>
                                  <%= image_tag "false.png", class: "img-tf" %>
                                <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>