config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
    resources :words
    root "static_pages#home"
  end
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :categories, only: [:index]
  resources :words, only: [:index, :show]
  resources :categories do
    resources :lessons
  end
  resources :lessons, only: [:index, :destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  scope :update_desc, ->{order updated_at: :desc}
  scope :search, ->search {where("name LIKE ?", "%#{search}%").update_desc}
  scope :alphabetically, ->{order :name}

  has_attached_file :category_img, styles: {category_index: "250x200",
    category_show: "400x350" }, default_url: "/images/:style/missing.png"

  validates :name, presence: true, length: {maximum: 140}
  validates_attachment_content_type :category_img, content_type: /\Aimage\/.*\z/

  def any_words_inside?
    self.words.any?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user, :logged_in_as_admin
  before_action :load_category, except: [:new, :create, :index]

  def index
    if params[:search]
      @categories = Category.search params[:search]
    else
      @categories = Category.alphabetically
    end
    @categories = @categories.paginate(page: params[:page])
      .per_page Settings.per_page.category
  end

  def new
    @category = Category.new
  end

  def show
    @words = @category.words.order_name.paginate(page: params[:page])
      .per_page Settings.per_page.words
  end

  def edit
  end

  def update
    if @category.update category_params
      flash[:success] = t "category_updated_success"
      redirect_to admin_category_path @category
    else
      render :edit
    end
  end

  def destroy
    if @category.any_words_inside?
      flash[:danger] = t "category_deleted_fail_cos_word"
    else
      if @category.destroy
        flash[:sucess] = t "category_deleted_success"
      else
        flash[:danger] = t "category_deleted_fail"
      end
    end
    redirect_to admin_categories_path
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:sucess] = t "category_created_success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :description, :category_img
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.alphabetically.paginate(page: params[:page])
      .per_page Settings.per_page.category
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.file_field :category_img %>
  <%= f.text_field :name, class: "form-control",
    placeholder: t("category_name") %>
  <%= f.text_area :description, class: "form-control",
    placeholder: t("category_description") %>
  <%= f.submit yield(:button_text), class: "btn btn-primary text-center" %>
<% end %>

app/views/admin/categories/_search_form.html.erb
<div id="search-form">
  <%= form_tag admin_categories_path, method: :get, class: "form-inline" do %>
    <%= text_field_tag :search, params[:search], class: "form-control" %>
    <%= submit_tag t("search"), class: "form-control" %>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :button_text, t("category_update") %>
<div class="category_content">
  <div class="omb_login">
    <h1 class="text-center "><%= t "category_edit" %></h1>
    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div id="wrapper" >
  <%= render "layouts/menu.html.erb" %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="search-form">
            <%= render "search_form" %>
          </div>
          <% @categories.each do |category| %>
            <div class="col-sm-4">
              <div class="thumbnail">
                <%= image_tag category.category_img.url(:category_index),
                  class: "category_img_index" %>
                <h4 class="text-center"><%= category.name %></h4>
                <div class="button_inline">
                  <%= link_to t("view"), admin_category_path(category),
                    class: "btn-flip btn btn-3d btn-primary" %>
                  <%= link_to t("edit"), edit_admin_category_path(category),
                    class: "btn-flip btn btn-3d btn-success" %>
                  <%= link_to t("delete"), admin_category_path(category),
                    class: "btn-flip btn btn-3d btn-danger", method: :delete,
                    data: {confirm: t("delete_message")} %>
                </div>
              </div>
            </div>
          <% end %>
          <%= will_paginate @categories %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to t("category_add"), new_admin_category_path %>
</div>

app/views/admin/categories/new.html.erb
<% provide :button_text, t("category_create") %>
<div class="category_content">
  <div class="omb_login">
    <h1 class="text-center "><%= t "category_create" %></h1>
    <div class="row omb_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container show_img">
  <h1 class="text-center"><%= t "category_information" %></h1>
  <div class="row category-info">
    <div class="col-md-4">
      <%= image_tag @category.category_img.url(:category_show),
        class: "category_img_show"%>
    </div>
    <div class="col-md-8">
      <div class="category_info">
        <h2><%= @category.name %></h2>
        <p><%= @category.description %></p>
        <%= link_to t("edit"), edit_admin_category_path(@category),
          class: "btn-flip btn btn-3d btn-primary" %>
        <%= link_to t("delete"), admin_category_path(@category), method: :delete,
          data: {confirm: t("delete_message")}, class: "btn-flip btn btn-3d btn-danger" %>
        <%= link_to t("back"), admin_categories_path,
          class: "btn-flip btn btn-3d btn-warning" %>
      </div>
    </div>
  </div>
  <div class="responsive-table category_info">
    <h2><%= t "word_list" %></h2>
    <table class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
      <tr>
        <th class="header-table"><%= t "word" %></th>
        <th class="header-table"><%= t "word_definition" %></th>
      </tr>
    </thead>
    <tbody>
      <% @words.each do |word| %>
        <tr>
          <td><%= word.name %></td>
          <td><%= word.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>