config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
    resources :words
    root "static_pages#home"
  end
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :categories, only: [:index]
  resources :words, only: [:index, :show]
  resources :categories do
    resources :lessons
  end
  resources :lessons, only: [:index, :destroy]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(:sample_app), "#", id: "logo" %>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
           data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= t "e_learning" %></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <% if logged_as_admin? %>
                <li>
                  <%= link_to t(:header_categories), admin_categories_path %>
                </li>
              <% else %>
                <li>
                  <%= link_to t(:header_categories), categories_path %>
                </li>
                <li>
                  <%= link_to t(:header_lesson), lessons_path %>
                </li>
              <% end %>
              <li><%= link_to t(:header_home), root_path %></li>
              <li><%= link_to @current_user.name, user_path(current_user) %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t "header_account" %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t(:header_profile), current_user %></li>
                  <li><%= link_to t(:header_settings), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t(:header_logout), logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to t(:home), root_path %></li>
              <li><%= link_to t(:header_log_in), login_path %></li>
              <li><%= link_to t(:header_sign_up), new_user_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_menu.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <a href="#"><%= t "infomation" %></a>
    </li>
    <li>
      <%= link_to t(:menu_users), users_path %>
    </li>
    <li>
      <%= link_to t(:menu_words), words_path %>
    </li>
    <li>
      <%= link_to t(:menu_categories), categories_path %>
    </li>
    <li>
      <%= link_to t(:menu_lessons), lessons_path %>
    </li>
    <li>
      <%= link_to t(:menu_activities), user_path(current_user) %>
    </li>
  </ul>
</div>
<button id="menu-toggle" ><%= t "Menu" %></button>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
    "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>